import type { Movie, MovieDetails } from './tmdb'

// All image paths verified from themoviedb.org
// backdrop_path=null → card falls back to poster_path (cropped 16:9)

export const MOCK_TRENDING: Movie[] = [
  { id: 155,    title: 'The Dark Knight',          poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg', overview: 'Batman raises the stakes in his war on crime. When the Joker, a criminal mastermind, wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', vote_average: 9.0, vote_count: 31000, popularity: 120, release_date: '2008-07-18', genre_ids: [18, 28, 80], media_type: 'movie' },
  { id: 27205,  title: 'Inception',                poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg', overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', vote_average: 8.8, vote_count: 35000, popularity: 110, release_date: '2010-07-16', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 1396,   name: 'Breaking Bad',              poster_path: '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg', backdrop_path: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg', overview: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.', vote_average: 9.5, vote_count: 14000, popularity: 400, first_air_date: '2008-01-20', genre_ids: [18, 80], media_type: 'tv' },
  { id: 157336, title: 'Interstellar',             poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg', overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.', vote_average: 8.7, vote_count: 34000, popularity: 105, release_date: '2014-11-07', genre_ids: [12, 18, 878], media_type: 'movie' },
  { id: 66732,  name: 'Stranger Things',           poster_path: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg', backdrop_path: null, overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.', vote_average: 8.7, vote_count: 18000, popularity: 380, first_air_date: '2016-07-15', genre_ids: [18, 9648, 10765], media_type: 'tv' },
  { id: 475557, title: 'Joker',                   poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg', overview: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', vote_average: 8.4, vote_count: 26000, popularity: 95, release_date: '2019-10-04', genre_ids: [80, 18], media_type: 'movie' },
  { id: 93405,  name: 'Squid Game',               poster_path: '/iE21DSI3n5vI6v1W2HT4feKoM97.jpg', backdrop_path: null, overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.', vote_average: 7.8, vote_count: 12500, popularity: 500, first_air_date: '2021-09-17', genre_ids: [10759, 18], media_type: 'tv' },
  { id: 278,    title: 'The Shawshank Redemption', poster_path: '/9cqNxx0GxF0bAY2MRw0KUGxrx2T.jpg', backdrop_path: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg', overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank State Penitentiary.', vote_average: 9.3, vote_count: 26000, popularity: 90, release_date: '1994-09-23', genre_ids: [18, 80], media_type: 'movie' },
  { id: 361743, title: 'Top Gun: Maverick',        poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', backdrop_path: null, overview: 'After more than thirty years of service as one of the Navy\'s top aviators, Pete "Maverick" Mitchell is where he belongs, pushing the envelope as a courageous test pilot.', vote_average: 8.3, vote_count: 10000, popularity: 200, release_date: '2022-05-27', genre_ids: [28, 18], media_type: 'movie' },
  { id: 496243, title: 'Parasite',                 poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', backdrop_path: null, overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the affluent and mysterious Park family and begins to infiltrate their lives one by one.', vote_average: 8.5, vote_count: 17000, popularity: 85, release_date: '2019-05-30', genre_ids: [35, 53, 18], media_type: 'movie' },
]

export const MOCK_POPULAR: Movie[] = [
  { id: 634649, title: 'Spider-Man: No Way Home',  poster_path: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg', overview: 'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a Super Hero. When he asks for help from Doctor Strange, the stakes become even more dangerous.', vote_average: 8.2, vote_count: 20000, popularity: 700, release_date: '2021-12-17', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 438631, title: 'Dune',                     poster_path: '/d5NXSklpcvkDKoL9lp8YpMmNSBs.jpg', backdrop_path: '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg', overview: 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family.', vote_average: 7.8, vote_count: 14000, popularity: 600, release_date: '2021-10-22', genre_ids: [12, 878], media_type: 'movie' },
  { id: 414906, title: 'The Batman',               poster_path: '/74xTEgt7R3BLzDqKFKRYMaRPiEF.jpg', backdrop_path: '/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg', overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.', vote_average: 7.8, vote_count: 12000, popularity: 550, release_date: '2022-03-04', genre_ids: [80, 18, 9648], media_type: 'movie' },
  { id: 24428,  title: 'The Avengers',             poster_path: null, backdrop_path: null, overview: 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, Director of the espionage agency S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink.', vote_average: 7.7, vote_count: 29000, popularity: 300, release_date: '2012-05-04', genre_ids: [878, 28, 12], media_type: 'movie' },
  { id: 299536, title: 'Avengers: Infinity War',   poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg', overview: 'Iron Man, Thor, the Hulk and the rest of the Avengers unite to battle their most powerful enemy yet — the evil Thanos.', vote_average: 8.3, vote_count: 28000, popularity: 280, release_date: '2018-04-27', genre_ids: [12, 878, 28], media_type: 'movie' },
  { id: 19995,  title: 'Avatar',                   poster_path: '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg', backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg', overview: 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', vote_average: 7.6, vote_count: 29000, popularity: 260, release_date: '2009-12-18', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 597,    title: 'Titanic',                  poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', backdrop_path: '/xnHVX37XZEp33hhCbYjqUupABb.jpg', overview: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', vote_average: 7.9, vote_count: 24000, popularity: 240, release_date: '1997-12-19', genre_ids: [18, 10749], media_type: 'movie' },
  { id: 603,    title: 'The Matrix',               poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', backdrop_path: null, overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', vote_average: 8.2, vote_count: 24000, popularity: 220, release_date: '1999-03-31', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 284054, title: 'Black Panther',            poster_path: '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg', backdrop_path: null, overview: 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and confront a challenger from his country\'s past.', vote_average: 7.3, vote_count: 22000, popularity: 200, release_date: '2018-02-16', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 530915, title: '1917',                     poster_path: '/iZf0KyrE25z1sage4SYQLAsbYvk.jpg', backdrop_path: null, overview: 'At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.', vote_average: 8.0, vote_count: 13000, popularity: 180, release_date: '2019-01-10', genre_ids: [28, 18, 10752], media_type: 'movie' },
]

export const MOCK_TOP_RATED: Movie[] = [
  { id: 238,   title: 'The Godfather',             poster_path: '/3bhkrj58Vtu7enYsLegofSPcVNr.jpg', backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime patriarch Vito Corleone barely survives an attempt on his life, his youngest son Michael steps in to take care of the assailant.', vote_average: 9.2, vote_count: 20000, popularity: 100, release_date: '1972-03-24', genre_ids: [18, 80], media_type: 'movie' },
  { id: 424,   title: "Schindler's List",          poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', backdrop_path: null, overview: 'The story of Oskar Schindler, a flamboyant German businessman who saved the lives of more than a thousand mostly Polish-Jewish refugees during the Holocaust by employing them in his factories.', vote_average: 9.0, vote_count: 15000, popularity: 95, release_date: '1993-12-15', genre_ids: [18, 10752], media_type: 'movie' },
  { id: 129,   title: 'Spirited Away',             poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg', overview: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', vote_average: 8.5, vote_count: 16000, popularity: 150, release_date: '2001-07-20', genre_ids: [16, 10751], media_type: 'movie' },
  { id: 680,   title: 'Pulp Fiction',              poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously intersect.', vote_average: 8.9, vote_count: 27000, popularity: 100, release_date: '1994-10-14', genre_ids: [18, 80], media_type: 'movie' },
  { id: 550,   title: 'Fight Club',                poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', backdrop_path: '/52AfXWuXCHn3UjD17rBruA9f5qb.jpg', overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.', vote_average: 8.8, vote_count: 28000, popularity: 105, release_date: '1999-10-15', genre_ids: [18], media_type: 'movie' },
  { id: 13,    title: 'Forrest Gump',              poster_path: '/h5J4W4veyxMXDMjeMLxcr7DJ0QR.jpg', backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg', overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events — in each case, however, his actions are hidden from the general public.', vote_average: 8.5, vote_count: 25000, popularity: 110, release_date: '1994-07-06', genre_ids: [18, 10749], media_type: 'movie' },
  { id: 98,    title: 'Gladiator',                 poster_path: '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', backdrop_path: null, overview: 'In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army\'s most capable and trusted generals and one of the few leaders his ailing emperor can trust.', vote_average: 8.5, vote_count: 20000, popularity: 100, release_date: '2000-05-05', genre_ids: [28, 18, 12], media_type: 'movie' },
  { id: 120,   title: 'The Lord of the Rings: The Fellowship of the Ring', poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', backdrop_path: null, overview: 'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil maker.', vote_average: 8.4, vote_count: 22000, popularity: 105, release_date: '2001-12-19', genre_ids: [12, 14, 28], media_type: 'movie' },
  { id: 274,   title: 'The Silence of the Lambs',  poster_path: '/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg', backdrop_path: null, overview: 'FBI trainee Clarice Starling works to unravel a psychopath\'s identity with the help of another: the brilliant and dangerous Dr. Hannibal Lecter.', vote_average: 8.3, vote_count: 16000, popularity: 95, release_date: '1991-02-14', genre_ids: [80, 18, 27, 53], media_type: 'movie' },
  { id: 87108, name: 'Chernobyl',                  poster_path: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg', backdrop_path: '/3URK9z9PzpVNJrGE7XOuyy6KFzk.jpg', overview: 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear disaster at Chernobyl. A tale of courageous men and women who sacrificed to save Europe from unimaginable disaster.', vote_average: 9.4, vote_count: 9000, popularity: 90, first_air_date: '2019-05-06', genre_ids: [18], media_type: 'tv' },
]

export const MOCK_TV: Movie[] = [
  { id: 1396,  name: 'Breaking Bad',               poster_path: '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg', backdrop_path: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg', overview: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.', vote_average: 9.5, vote_count: 14000, popularity: 400, first_air_date: '2008-01-20', genre_ids: [18, 80], media_type: 'tv' },
  { id: 1399,  name: 'Game of Thrones',            poster_path: '/seGbGCqUI1DzYndRekrpuBQS64k.jpg', backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg', overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.', vote_average: 9.3, vote_count: 22000, popularity: 380, first_air_date: '2011-04-17', genre_ids: [10759, 18, 10765], media_type: 'tv' },
  { id: 66732, name: 'Stranger Things',            poster_path: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg', backdrop_path: null, overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.', vote_average: 8.7, vote_count: 18000, popularity: 360, first_air_date: '2016-07-15', genre_ids: [18, 9648, 10765], media_type: 'tv' },
  { id: 93405, name: 'Squid Game',                 poster_path: '/iE21DSI3n5vI6v1W2HT4feKoM97.jpg', backdrop_path: null, overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children\'s games. Inside, a tempting prize awaits — with deadly high stakes.', vote_average: 7.8, vote_count: 12500, popularity: 500, first_air_date: '2021-09-17', genre_ids: [10759, 18], media_type: 'tv' },
  { id: 82856, name: 'The Mandalorian',            poster_path: '/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg', backdrop_path: '/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg', overview: 'After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.', vote_average: 8.5, vote_count: 11000, popularity: 340, first_air_date: '2019-11-12', genre_ids: [10759, 10765], media_type: 'tv' },
  { id: 65494, name: 'The Crown',                  poster_path: '/1M876KPjulVwppEpldhdc8V4o68.jpg', backdrop_path: '/8VXhcrl5z2I1zEU9X3pkkNrZlD.jpg', overview: 'This drama follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.', vote_average: 8.1, vote_count: 5000, popularity: 200, first_air_date: '2016-11-04', genre_ids: [18], media_type: 'tv' },
  { id: 71446, name: 'Money Heist',                poster_path: '/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg', backdrop_path: '/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg', overview: 'A mysterious criminal mastermind known as "The Professor" recruits a gang of eight robbers who have nothing to lose in order to execute an ambitious plan to print billions of euros in the Royal Mint of Spain.', vote_average: 8.3, vote_count: 8000, popularity: 320, first_air_date: '2017-05-02', genre_ids: [80, 18, 9648], media_type: 'tv' },
  { id: 70523, name: 'Dark',                       poster_path: '/1DLjjvSWMYo17B7wuz6YikB96hH.jpg', backdrop_path: '/3jDXL4Xvj3AzDOF6UH1xeyHW8MH.jpg', overview: 'A missing child sets four estranged families on a frantic hunt for answers as they unearth a sinister time travel conspiracy which spans several generations.', vote_average: 8.7, vote_count: 7000, popularity: 180, first_air_date: '2017-12-01', genre_ids: [18, 9648, 10765], media_type: 'tv' },
  { id: 2316,  name: 'The Office',                 poster_path: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', backdrop_path: '/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg', overview: 'The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.', vote_average: 8.9, vote_count: 7000, popularity: 250, first_air_date: '2005-03-24', genre_ids: [35], media_type: 'tv' },
  { id: 87108, name: 'Chernobyl',                  poster_path: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg', backdrop_path: '/3URK9z9PzpVNJrGE7XOuyy6KFzk.jpg', overview: 'The true story of one of the worst man-made catastrophes in history. A tale of courageous men and women who sacrificed to save Europe from unimaginable disaster.', vote_average: 9.4, vote_count: 9000, popularity: 170, first_air_date: '2019-05-06', genre_ids: [18], media_type: 'tv' },
]

export const MOCK_ACTION: Movie[] = [
  { id: 155,   title: 'The Dark Knight',           poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg', overview: 'Batman raises the stakes in his war on crime. When the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', vote_average: 9.0, vote_count: 31000, popularity: 120, release_date: '2008-07-18', genre_ids: [18, 28, 80], media_type: 'movie' },
  { id: 24428, title: 'The Avengers',              poster_path: null, backdrop_path: null, overview: 'Earth\'s mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki and his alien army from enslaving humanity.', vote_average: 7.7, vote_count: 29000, popularity: 300, release_date: '2012-05-04', genre_ids: [878, 28, 12], media_type: 'movie' },
  { id: 98,    title: 'Gladiator',                 poster_path: '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg', backdrop_path: null, overview: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', vote_average: 8.5, vote_count: 20000, popularity: 100, release_date: '2000-05-05', genre_ids: [28, 18, 12], media_type: 'movie' },
  { id: 361743,title: 'Top Gun: Maverick',         poster_path: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg', backdrop_path: null, overview: 'After more than thirty years of service as one of the Navy\'s top aviators, Pete "Maverick" Mitchell is pushing the envelope as a courageous test pilot.', vote_average: 8.3, vote_count: 10000, popularity: 200, release_date: '2022-05-27', genre_ids: [28, 18], media_type: 'movie' },
  { id: 603,   title: 'The Matrix',                poster_path: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', backdrop_path: null, overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', vote_average: 8.2, vote_count: 24000, popularity: 220, release_date: '1999-03-31', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 19995, title: 'Avatar',                    poster_path: '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg', backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg', overview: 'A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', vote_average: 7.6, vote_count: 29000, popularity: 260, release_date: '2009-12-18', genre_ids: [28, 12, 878], media_type: 'movie' },
  { id: 120,   title: 'The Lord of the Rings: The Fellowship of the Ring', poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', backdrop_path: null, overview: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', vote_average: 8.4, vote_count: 22000, popularity: 105, release_date: '2001-12-19', genre_ids: [12, 14, 28], media_type: 'movie' },
  { id: 414906,title: 'The Batman',                poster_path: '/74xTEgt7R3BLzDqKFKRYMaRPiEF.jpg', backdrop_path: '/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg', overview: 'When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption.', vote_average: 7.8, vote_count: 12000, popularity: 550, release_date: '2022-03-04', genre_ids: [80, 18, 9648], media_type: 'movie' },
]

export const MOCK_COMEDY: Movie[] = [
  { id: 120467,title: 'The Grand Budapest Hotel',  poster_path: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg', backdrop_path: null, overview: 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', vote_average: 8.1, vote_count: 16000, popularity: 95, release_date: '2014-03-07', genre_ids: [35, 80, 12], media_type: 'movie' },
  { id: 771,   title: 'Home Alone',                poster_path: '/a4c3X5WY3sdov69SDi0W78jAUHC.jpg', backdrop_path: null, overview: 'Eight-year-old Kevin McCallister is accidentally left behind when his family rushes to the airport to fly to Paris for Christmas vacation.', vote_average: 7.4, vote_count: 11000, popularity: 100, release_date: '1990-11-16', genre_ids: [35, 10751], media_type: 'movie' },
  { id: 8363,  title: 'Superbad',                  poster_path: '/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg', backdrop_path: null, overview: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.', vote_average: 7.6, vote_count: 8000, popularity: 85, release_date: '2007-08-17', genre_ids: [35], media_type: 'movie' },
  { id: 18785, title: 'The Hangover',              poster_path: '/A0uS9rHR56FeBtpjVki16M5xxSW.jpg', backdrop_path: null, overview: 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.', vote_average: 7.7, vote_count: 12000, popularity: 90, release_date: '2009-06-05', genre_ids: [35, 80], media_type: 'movie' },
  { id: 2316,  name: 'The Office',                 poster_path: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg', backdrop_path: '/mLyW3UTgi2lsMdtueYODcfAB9Ku.jpg', overview: 'The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.', vote_average: 8.9, vote_count: 7000, popularity: 250, first_air_date: '2005-03-24', genre_ids: [35], media_type: 'tv' },
  { id: 13,    title: 'Forrest Gump',              poster_path: '/h5J4W4veyxMXDMjeMLxcr7DJ0QR.jpg', backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg', overview: 'A man with a low IQ has accomplished great things in his life and been present during significant historic events.', vote_average: 8.5, vote_count: 25000, popularity: 110, release_date: '1994-07-06', genre_ids: [18, 10749], media_type: 'movie' },
  { id: 496243,title: 'Parasite',                  poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', backdrop_path: null, overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the affluent and mysterious Park family. A darkly comic thriller about class warfare.', vote_average: 8.5, vote_count: 17000, popularity: 85, release_date: '2019-05-30', genre_ids: [35, 53, 18], media_type: 'movie' },
]

export const MOCK_HORROR: Movie[] = [
  { id: 419430, title: 'Get Out',                  poster_path: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg', backdrop_path: null, overview: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.', vote_average: 7.7, vote_count: 9000, popularity: 130, release_date: '2017-02-24', genre_ids: [27, 9648, 53], media_type: 'movie' },
  { id: 447332, title: 'A Quiet Place',            poster_path: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg', backdrop_path: null, overview: 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.', vote_average: 7.5, vote_count: 11000, popularity: 120, release_date: '2018-04-06', genre_ids: [27, 9648, 18], media_type: 'movie' },
  { id: 346364, title: 'It',                       poster_path: '/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg', backdrop_path: '/tcheoB1yt4GKtVQRoFMvhyCVUiY.jpg', overview: 'In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town.', vote_average: 7.3, vote_count: 16000, popularity: 110, release_date: '2017-09-08', genre_ids: [27, 18], media_type: 'movie' },
  { id: 138843, title: 'The Conjuring',            poster_path: '/wVYREutTvI2tmxr6ujrHT704wGF.jpg', backdrop_path: '/nVRyd8hlg0ZLxBn9RaI7mVMsDFW.jpg', overview: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.', vote_average: 7.5, vote_count: 10000, popularity: 105, release_date: '2013-07-19', genre_ids: [27, 53], media_type: 'movie' },
  { id: 274,    title: 'The Silence of the Lambs', poster_path: '/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg', backdrop_path: null, overview: 'FBI trainee Clarice Starling works to unravel a psychopath\'s identity with the help of another: the brilliant and dangerous Dr. Hannibal Lecter.', vote_average: 8.3, vote_count: 16000, popularity: 95, release_date: '1991-02-14', genre_ids: [80, 18, 27, 53], media_type: 'movie' },
  { id: 475557, title: 'Joker',                    poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg', backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg', overview: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.', vote_average: 8.4, vote_count: 26000, popularity: 95, release_date: '2019-10-04', genre_ids: [80, 18], media_type: 'movie' },
  { id: 539681, title: 'Nope',                     poster_path: '/AcKVlWaNVVVFQwynSr1DgpMuIMz.jpg', backdrop_path: null, overview: 'Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery. A western epic of spectacle and wonder, horror and humor.', vote_average: 6.9, vote_count: 5000, popularity: 80, release_date: '2022-07-22', genre_ids: [27, 9648, 878], media_type: 'movie' },
]

export const MOCK_DOCS: Movie[] = [
  { id: 426117, title: 'Free Solo',                poster_path: '/xZM4J0iJNdTVgW1AnshGTI2Fnjf.jpg', backdrop_path: null, overview: 'Follow Alex Honnold as he attempts to become the first person to ever free solo climb Yosemite\'s El Capitan — a 3,000-foot granite wall — with no ropes or safety gear of any kind.', vote_average: 8.2, vote_count: 3500, popularity: 100, release_date: '2018-09-28', genre_ids: [99], media_type: 'movie' },
  { id: 68595,  name: 'Planet Earth II',           poster_path: '/5maYKYzWpE68ycxGh1luu4P2LOS.jpg', backdrop_path: null, overview: 'Sir David Attenborough presents a stunning look at animals inhabiting a variety of environments, from snow-capped mountains to lonely islands.', vote_average: 9.5, vote_count: 4000, popularity: 95, first_air_date: '2016-11-06', genre_ids: [99], media_type: 'tv' },
  { id: 244786, title: 'Blackfish',                poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg', backdrop_path: null, overview: 'A documentary following the controversial captivity of killer whales, and its dangers for both humans and whales.', vote_average: 8.1, vote_count: 2500, popularity: 85, release_date: '2013-01-19', genre_ids: [99], media_type: 'movie' },
  { id: 87108,  name: 'Chernobyl',                 poster_path: '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg', backdrop_path: '/3URK9z9PzpVNJrGE7XOuyy6KFzk.jpg', overview: 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear disaster at Chernobyl.', vote_average: 9.4, vote_count: 9000, popularity: 90, first_air_date: '2019-05-06', genre_ids: [18], media_type: 'tv' },
  { id: 72105,  title: 'Samsara',                  poster_path: '/byFNMZFtQ79bC2l0p5UGzfIjqjk.jpg', backdrop_path: null, overview: 'A non-narrative film that explores the wonders of our world through imagery taken in over 25 countries across 5 continents over a period of 5 years.', vote_average: 8.3, vote_count: 3200, popularity: 70, release_date: '2012-08-24', genre_ids: [99], media_type: 'movie' },
  { id: 49018,  title: 'Searching for Sugar Man',  poster_path: '/oOsLzUCMuZxNjEhYKfuMNAjFLW7.jpg', backdrop_path: null, overview: 'Two South Africans set out to discover what happened to their musical hero, the mysterious 1970s rock musician Rodriguez.', vote_average: 8.2, vote_count: 2800, popularity: 75, release_date: '2012-07-27', genre_ids: [99, 10402], media_type: 'movie' },
]

export const MOCK_ANIMATION: Movie[] = [
  { id: 129,    title: 'Spirited Away',             poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', backdrop_path: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg', overview: 'Chihiro and her parents are moving to a small Japanese town in the countryside. On the way, they discover what appears to be an abandoned amusement park. Chihiro enters a spirit world.', vote_average: 8.5, vote_count: 16000, popularity: 150, release_date: '2001-07-20', genre_ids: [16, 10751], media_type: 'movie' },
  { id: 10681,  title: 'WALL·E',                   poster_path: '/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg', backdrop_path: '/vSdhorIOsMflYfEbhXqCbbyLkrm.jpg', overview: 'WALL-E is the last robot left on an Earth that has been abandoned by humans. He falls in love with EVE, a sleek probe sent back to Earth on a scanning mission.', vote_average: 8.4, vote_count: 15000, popularity: 140, release_date: '2008-06-27', genre_ids: [16, 10751, 878], media_type: 'movie' },
  { id: 14160,  title: 'Up',                       poster_path: '/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg', backdrop_path: null, overview: 'Carl Fredricksen, a 78-year-old balloon salesman, and Russell, a young Wilderness Explorer, soar over mountains and jungles, finally arriving at a lost world.', vote_average: 8.3, vote_count: 18000, popularity: 135, release_date: '2009-05-29', genre_ids: [16, 10751, 12], media_type: 'movie' },
  { id: 862,    title: 'Toy Story',                poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', backdrop_path: '/7nPQTxC5bZJSpt6QBaZGD8mvTyK.jpg', overview: 'Led by Woody, Andy\'s toys live happily in his room until Andy\'s birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy\'s heart, Woody plots against Buzz.', vote_average: 8.3, vote_count: 16000, popularity: 130, release_date: '1995-11-22', genre_ids: [16, 10751, 12], media_type: 'movie' },
  { id: 8587,   title: 'The Lion King',            poster_path: '/sCanFMnL3fOrXQiuFWbDZBT1PNr.jpg', backdrop_path: '/wXgiFxsFX8mMPKtFpIRPGaUfnEu.jpg', overview: 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah.', vote_average: 8.5, vote_count: 18000, popularity: 160, release_date: '1994-06-24', genre_ids: [16, 10751, 18], media_type: 'movie' },
  { id: 12,     title: 'Finding Nemo',             poster_path: '/eHuGQ10FUzK1p9jhMcgSC8YjBpQ.jpg', backdrop_path: '/upMbhQZHClbCYE9x4Nvao8fUDJv.jpg', overview: 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', vote_average: 8.2, vote_count: 16000, popularity: 125, release_date: '2003-05-30', genre_ids: [16, 10751, 12], media_type: 'movie' },
  { id: 920,    title: 'Cars',                     poster_path: '/1JEbxQbQhwcXm5DZ0Pb5gHoLRKE.jpg', backdrop_path: null, overview: 'On the way to the biggest race of his life, a hotshot rookie race car gets stranded in a rundown town and learns that winning isn\'t everything in life.', vote_average: 7.2, vote_count: 10000, popularity: 100, release_date: '2006-06-09', genre_ids: [16, 10751, 12], media_type: 'movie' },
]

export const ALL_MOCK = [
  ...MOCK_TRENDING,
  ...MOCK_POPULAR,
  ...MOCK_TOP_RATED,
  ...MOCK_TV,
  ...MOCK_ACTION,
  ...MOCK_COMEDY,
  ...MOCK_HORROR,
  ...MOCK_DOCS,
  ...MOCK_ANIMATION,
]

export function mockSearch(query: string): Movie[] {
  const q = query.toLowerCase()
  const seen = new Set<number>()
  return ALL_MOCK.filter(m => {
    const title = (m.title || m.name || '').toLowerCase()
    const overview = m.overview.toLowerCase()
    if (!title.includes(q) && !overview.includes(q)) return false
    if (seen.has(m.id)) return false
    seen.add(m.id)
    return true
  })
}

export function mockGetDetails(id: number): MovieDetails {
  const found = ALL_MOCK.find(m => m.id === id)
  const base: Movie = found || {
    id, title: 'Unknown', overview: '', poster_path: null, backdrop_path: null,
    vote_average: 0, vote_count: 0, popularity: 0,
  }
  return {
    ...base,
    genres: (base.genre_ids || []).map(gid => GENRE_MAP[gid] || { id: gid, name: 'Unknown' }),
    videos: { results: [] },
    credits: { cast: [] },
    similar: { results: MOCK_TRENDING.filter(m => m.id !== id).slice(0, 12) },
  }
}

const GENRE_MAP: Record<number, { id: number; name: string }> = {
  28: { id: 28, name: 'Action' },
  12: { id: 12, name: 'Adventure' },
  16: { id: 16, name: 'Animation' },
  35: { id: 35, name: 'Comedy' },
  80: { id: 80, name: 'Crime' },
  99: { id: 99, name: 'Documentary' },
  18: { id: 18, name: 'Drama' },
  10751: { id: 10751, name: 'Family' },
  14: { id: 14, name: 'Fantasy' },
  27: { id: 27, name: 'Horror' },
  10402: { id: 10402, name: 'Music' },
  9648: { id: 9648, name: 'Mystery' },
  10749: { id: 10749, name: 'Romance' },
  878: { id: 878, name: 'Science Fiction' },
  53: { id: 53, name: 'Thriller' },
  10752: { id: 10752, name: 'War' },
  10759: { id: 10759, name: 'Action & Adventure' },
  10765: { id: 10765, name: 'Sci-Fi & Fantasy' },
}
